<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@865.v43e78cc44e0d">
  <node class="cps.n.StepAtomNode" plugin="workflow-cps@3793.v65dec41c3a_c3">
    <parentIds>
      <string>38</string>
    </parentIds>
    <id>39</id>
    <descriptorId>org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep</descriptorId>
  </node>
  <actions>
    <cps.a.ArgumentsActionImpl plugin="workflow-cps@3793.v65dec41c3a_c3">
      <arguments>
        <entry>
          <string>script</string>
          <string>
                        set +x
                        cd MultiRegion
                        rm -rf terraform*
                        terraform init -backend-config=&quot;access_key=${AWS_ACCESS_KEY_ID}&quot; -backend-config=&quot;secret_key=${AWS_SECRET_ACCESS_KEY}&quot; -backend-config=&quot;region=${s3backendregion}&quot; -backend-config=&quot;bucket=${s3backendbucketname}&quot; -backend-config=&quot;key=terraform.tfstate&quot;
                    </string>
        </entry>
      </arguments>
      <sensitiveVariables>
        <string>AWS_ACCESS_KEY_ID</string>
        <string>AWS_SECRET_ACCESS_KEY</string>
      </sensitiveVariables>
      <isUnmodifiedBySanitization>true</isUnmodifiedBySanitization>
    </cps.a.ArgumentsActionImpl>
    <wf.a.TimingAction plugin="workflow-api@1283.v99c10937efcb_">
      <startTime>1696439982436</startTime>
    </wf.a.TimingAction>
    <s.a.LogStorageAction/>
    <wf.a.ErrorAction plugin="workflow-api@1283.v99c10937efcb_">
      <error class="hudson.AbortException">
        <detailMessage>script returned exit code 1</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:668)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:614)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:555)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
        </stackTrace>
        <suppressedExceptions>
          <wf.a.ErrorAction_-ErrorId>
            <stackTrace/>
            <suppressedExceptions class="empty-list"/>
            <uuid>54d7d5a9-8487-4f63-ad33-71950983320f</uuid>
          </wf.a.ErrorAction_-ErrorId>
        </suppressedExceptions>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>